# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.9.0]
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Lint Check
      id: lint-check
      run: yarn lint
    - name: Lint fail check
      if: steps.lint-check.status == 'failure'
      run: exit 1
    - name: Run prettier
      run: yarn prettier
    - run: npm run build --if-present
    # - run: npm test

