name: Close stale issues and PR's
on:
  pull_request:
    branches:
      - "main"
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
permissions:
  issues: write
  pull-requests: write
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@4.0.0
        with:
          repo-token: ${{env.GITHUB_TOKEN}}
          days-before-stale: 30
